Repository keymanapp/shared-sites, pull requests merged in 2024-12, with the labels that each got.

#47 docs: update for new alerts
  _common/README.md
  _common/assets/img/gfm-limits-1.png
  _common/assets/img/gfm-limits-2.png
  _common/assets/img/gfm-limits-3.png
  _common/assets/img/gfm-limits-4.png
  _common/assets/img/gfmalerts.png
Labels: documentation

#41 feat: integrate GFM-style alerts (#40) v0.12
  _common/GFMAlerts.php
  _common/MarkdownHost.php
  _common/README.md
  _common/assets/img/gfm-limits-1.png
  _common/assets/img/gfm-limits-2.png
  _common/assets/img/gfm-limits-3.png
  _common/assets/img/gfm-limits-4.png
  _common/assets/img/gfmalerts.png
  bootstrap.inc.sh
Labels: feat

#50 fix: crash in GFMAlerts when falling back to blockquote
  _common/GFMAlerts.php
Labels: fix
